### ISSUE TITLE
Different tokenizer

### ISSUE THREAD

**Issue by thangld201** [edchengg/easyproject#1]
Hi @edchengg, I realized that with the nllb-easyproject models (e.g. `ychenNLP/nllb-200-3.3B-easyproject`), using the default tokenizer files would yield bad results, and one has to use the original nllb tokenizers (e.g. `facebook/nllb-200-distilled-600M`). Although examples were given, I am curious as why we have to do this ?

**Comment by edchengg** [comment]
Thanks for noting this! I didn't realize this issue actually. I guess there might be some config issue during model uploading or saving.
